config/routes.rb
Rails.application.routes.draw do
  #general routes
  root to: "welcome#index"
  resources :items, only: [:index, :show, :destroy]
  resources :orders, only: [:show, :update]

  #merchant routes
  resources :items, only: [:new, :create, :index, :show, :destroy]

  resources :merchants, only: [:index, :show] do
    resources :items, only: [:show]
  end

  get '/dashboard', to: 'merchants#show', as: :dashboard
  get '/dashboard/orders/:id', to: 'merchants/orders#show', as: :dashboard_order
  get '/dashboard/items', to: 'merchants/items#index', as: :dashboard_items
  get '/dashboard/items/new', to: 'merchants/items#new', as: :new_merchant_item
  get '/dashboard/items/:id/edit', to: 'merchants/items#edit', as: :edit_item
  patch '/dashboard/items/:id/edit', to: 'merchants/items#update'
  get '/enable_item/:id', to: 'merchants/items#enable_item', as: :enable_item
  get '/fulfill_item/:id', to: 'merchants/items#fulfill_item', as: :fulfill_item
  get '/delete_item/:id', to: 'merchants/items#delete_item', as: :delete_item
  get '/disable_item/:id', to: 'merchants/items#disable_item', as: :disable_item

  #admin routes
  namespace :admin do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    resources :merchants, only: [:show, :update]
    resources :users, only: [:show, :index, :update]
  end

  #cart routes
  get '/cart', to: "cart#index", as: :cart
  get '/emptycart', to: "cart#destroy", as: :empty_cart
  get '/remove_item/:id', to: "cart#remove_item", as: :remove_item
  get '/increment_item/:id', to: "cart#increment_item", as: :increment_item
  get '/decrement_item/:id', to: "cart#decrement_item", as: :decrement_item
  get '/checkout', to: "cart#checkout", as: :checkout

  #user routes
  get '/profile', to: "users#show", as: :profile
  get '/profile/edit', to: "users#edit", as: :edit_profile
  get '/profile/orders', to: "orders#index", as: :profile_orders
  get '/profile/orders/:id', to: "orders#show", as: :profile_order
  resources :cart, only: [:create]

  #all users routes
  get '/login', to: "sessions#new", as: :login
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: :logout
  get '/register', to: "users#new", as: :registration
  resources :users, only: [:new, :create, :edit, :update] do
    resources :items, only: [:create]
  end

end

app/models/cart.rb
class Cart
  attr_reader :contents

  def initialize(initial_contents)
    @contents = initial_contents || Hash.new(0)
    @contents.default = 0
  end

  def total_count
    @contents.values.sum
  end

  def add_item(id)
    @contents[id.to_s] = @contents[id.to_s] + 1
  end

  def deduct_item(id)
    @contents[id.to_s] -= 1
    @contents.delete(id.to_s) if @contents[id.to_s] == 0
  end

  def count_of(id)
    @contents[id.to_s].to_i
  end

  def items
    items_hash = Hash.new(0)
    @contents.each do |item_id, quantity|
      item = Item.find(item_id)
      items_hash[item] = quantity
    end
    items_hash
  end

  def grand_total
    items.sum { |item, quantity| item.price * quantity }
  end

  def empty?
    @contents.count == 0
  end

  def empty_cart
    @contents.clear
  end

  def generate_order(user)
    order = user.orders.create

    self.items.each do |item, quantity|
      order.order_items.create(
        item_id: item.id,
        order_price: item.price,
        quantity: quantity
      )
    end
  end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include ActionView::Helpers::TextHelper

  def index
    render file: "/public/404", status: 404 if merchant_user? || admin_user?
    if @cart.empty?
      flash[:cart_empty] = "Your cart is empty."
    end
  end

  def create
    item = Item.find(params[:item_id])
    @cart.add_item(item.id)
    session[:cart] = @cart.contents
    quantity = @cart.count_of(item.id)

    flash[:notice] = "You now have #{pluralize(quantity, "copy")} of #{item.name} in your cart."
    redirect_to items_path
  end

  def destroy
    @cart.empty_cart

    redirect_to cart_path
  end

  def remove_item
    @cart.contents.delete(params[:id]) # Remove item.id from @contents

    redirect_to cart_path
  end

  def increment_item
    item = Item.find(params[:id])

    if @cart.count_of(item.id) < item.quantity # Check there is stock of item available
      @cart.add_item(item.id)
    else
      flash[:out_of_stock] = "You have reached the maximum stock available currently for #{item.name}."
    end

    redirect_to cart_path
  end

  def decrement_item
    item = Item.find(params[:id])

    if @cart.count_of(item.id) > 1
      @cart.deduct_item(item.id)
    else
      @cart.contents.delete(params[:id])
    end

    redirect_to cart_path
  end

  def checkout
    @cart.generate_order(current_user)

    flash[:order_created_success] = "Your order was created successfully."

    @cart.empty_cart

    redirect_to profile_orders_path
  end
end

app/views/cart/index.html.erb
<header class = "cart-header">
  <% unless current_user %>
    <section id='register-or-login-to-checkout'>
      <p>You must <%= link_to "Register", new_user_path %> or <%= link_to "Login", login_path %> to checkout.</p>
    </section>
  <% end %>
  <% unless @cart.empty? %>
    <%= link_to "Empty Cart", empty_cart_path %>
    <% if current_reguser? %>
      <%= link_to "Checkout", checkout_path %>
    <% end %>
  <% end %>
</header>
<h1>Cart</h1>
<section id = "items-container">
  <% @cart.items.each do |item, quantity| %>
    <section class = "cart-container" id="cart-item-<%= item.id %>">
      <section id = "cart-header">
        <h3><%= link_to item.name, item_path(item) %> </h3>
        <%= link_to image_tag(item.image_url, class: "small-image", alt: "Image of #{item.name}"), item_path(item) %>
        <p><%= link_to "Remove Item From Cart", remove_item_path(item) %></p>
      </section>
      <p>Merchant: <%= item.user.name %></p>
      <p>Unit Price: <%= number_to_currency(item.price) %></p>
      <section class = "quantity">
        <p>Quantity: <%= quantity %>
          <ul>
            <li><%= link_to "+", increment_item_path(item) %></li>
            <li><%= link_to "-", decrement_item_path(item) %></li>
          </ul>
        </p>
      </section>
      <p>Subtotal: <%= number_to_currency(item.subtotal(quantity)) %></p>
    </section>
  <% end %>
</section>

<% unless @cart.empty? %>
  <h5 class = "grand-total">Grand Total: <%= number_to_currency(@cart.grand_total) %></h5>
<% end %>