config/routes.rb
Rails.application.routes.draw do
  #general routes
  root to: "welcome#index"
  resources :items, only: [:index, :show, :destroy]
  resources :orders, only: [:show, :update]

  #merchant routes
  resources :items, only: [:new, :create, :index, :show, :destroy]

  resources :merchants, only: [:index, :show] do
    resources :items, only: [:show]
  end

  get '/dashboard', to: 'merchants#show', as: :dashboard
  get '/dashboard/orders/:id', to: 'merchants/orders#show', as: :dashboard_order
  get '/dashboard/items', to: 'merchants/items#index', as: :dashboard_items
  get '/dashboard/items/new', to: 'merchants/items#new', as: :new_merchant_item
  get '/dashboard/items/:id/edit', to: 'merchants/items#edit', as: :edit_item
  patch '/dashboard/items/:id/edit', to: 'merchants/items#update'
  get '/enable_item/:id', to: 'merchants/items#enable_item', as: :enable_item
  get '/fulfill_item/:id', to: 'merchants/items#fulfill_item', as: :fulfill_item
  get '/delete_item/:id', to: 'merchants/items#delete_item', as: :delete_item
  get '/disable_item/:id', to: 'merchants/items#disable_item', as: :disable_item

  #admin routes
  namespace :admin do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    resources :merchants, only: [:show, :update]
    resources :users, only: [:show, :index, :update]
  end

  #cart routes
  get '/cart', to: "cart#index", as: :cart
  get '/emptycart', to: "cart#destroy", as: :empty_cart
  get '/remove_item/:id', to: "cart#remove_item", as: :remove_item
  get '/increment_item/:id', to: "cart#increment_item", as: :increment_item
  get '/decrement_item/:id', to: "cart#decrement_item", as: :decrement_item
  get '/checkout', to: "cart#checkout", as: :checkout

  #user routes
  get '/profile', to: "users#show", as: :profile
  get '/profile/edit', to: "users#edit", as: :edit_profile
  get '/profile/orders', to: "orders#index", as: :profile_orders
  get '/profile/orders/:id', to: "orders#show", as: :profile_order
  resources :cart, only: [:create]

  #all users routes
  get '/login', to: "sessions#new", as: :login
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: :logout
  get '/register', to: "users#new", as: :registration
  resources :users, only: [:new, :create, :edit, :update] do
    resources :items, only: [:create]
  end

end

app/controllers/admin/merchants_controller.rb
class Admin::MerchantsController < Admin::BaseController

  def show
    @user = User.find(params[:id])
    redirect_to admin_user_path(@user) if @user.user?
  end

  def update
    merchant = User.find(params[:id])
    if params[:disable]
      merchant.disable_merchant_items
      merchant.update(enabled: false)
      flash[:merchant_disabled] = "#{merchant.name} is now disabled"
      redirect_to merchants_path
    elsif params[:enable]
      merchant.update(enabled: true)
      merchant.enable_merchant_items
      flash[:merchant_enabled] = "#{merchant.name} is now enabled"
      redirect_to merchants_path
    elsif params[:downgrade]
      merchant.disable_merchant_items
      merchant.update(role: 0)
      flash[:notice] = "Merchant #{merchant.name} downgraded."
      redirect_to admin_user_path(merchant)
    end
  end
end

app/controllers/merchants/base_controller.rb
class Merchants::BaseController < ApplicationController
  before_action :require_merchant

  private

  def require_merchant
     render file: "/public/404", status: 404 unless merchant_user?
  end
end

app/controllers/merchants/items_controller.rb
class Merchants::ItemsController < Merchants::BaseController

  def index
    @merchant = current_user
  end

  def new
    @merchant = current_user
    @item = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])


    if @item.update(item_params)
      flash[:success] = "Item updated successfully."

      redirect_to dashboard_items_path
    else
      flash[:error] = @item.errors.full_messages.join(", ")
      @item = Item.find(params[:id])

      render :edit
    end
  end

  def enable_item
    item = Item.find(params[:id])
    item.update(enabled: true)

    flash[:item_enable_success] = "#{item.name} is now available for sale."

    redirect_to dashboard_items_path
  end

  def fulfill_item
    order_item = OrderItem.find(params[:order_item])
    order_item.fulfill_item

    flash[:item_fulfilled_success] = "Item #{order_item.item.name} has been fulfilled successfully."

    order = Order.find(params[:order])
    redirect_to dashboard_order_path(order)
  end

  def delete_item
    item = Item.find(params[:id])
    item.destroy

    flash[:item_delete_success] = "#{item.name} has been deleted."

    redirect_to dashboard_items_path
  end

  def disable_item
    item = Item.find(params[:id])
    item.update(enabled: false)

    flash[:item_disable_success] = "#{item.name} is no longer for sale."

    redirect_to dashboard_items_path
  end

  private

  def item_params
    ip = params.require(:item).permit(:name, :description, :image_url, :quantity, :price)
    if ip[:image_url].blank?
      ip[:image_url] = "https://i.pinimg.com/originals/2a/84/90/2a849069c7f487f71bb6594dffb84e5e.png"
    end

    ip
  end
end

app/controllers/merchants/orders_controller.rb
class Merchants::OrdersController < Merchants::BaseController
  def show
    @order = Order.find(params[:id])
    items = @order.items.where(user: current_user)

    @merchant_items = {}

    items.each do |item|
      @merchant_items[item] = @order.order_items.find_by(item_id: item)
    end
  end
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @merchants = User.where(role: 'merchant', enabled: true)
    @merchants_disabled = User.where(role: 'merchant', enabled: false) if admin_user?
  end

  def show
    if merchant_user?
      @user = User.find(current_user.id)
      @pending_orders = @user.pending_orders
      @top_five_items_sold = @user.top_five_items_sold
      @best_customer_by_orders = @user.best_customer_by_orders
      @best_customer_by_items = @user.best_customer_by_items
      @best_customers_by_revenue = @user.best_customers_by_revenue
    else
      render file: "/public/404", status: 404
    end
  end
end

app/views/merchants/index.html.erb
<h1>Merchants</h1>
<section class = "items-container">
  <% @merchants.each do |merchant| %>
    <section class = "item-card" id='merchant-<%= merchant.id %>'>
        <h3 class="bg-dark text-white" >
        <% if admin_user? %>
            <%= link_to merchant.name, admin_merchant_path(merchant) %>
        <% else %>
          <%= link_to merchant.name, merchant_path(merchant) %>
        <% end %></h3>
      <ul>
        <% if admin_user? %>
          <li><%= link_to 'Disable', admin_merchant_path(merchant, disable: true), method: :patch %></li>
        <% end %>
        <li>City: <%= merchant.city%></li>
        <li>State: <%= merchant.state%></li>
        <li>Enrolled since: <%= merchant.created_at%></li>
      </ul>
    </section>
  <% end %>
  <% if admin_user? %>
    <h1>Disabled Merchants</h1>
    <% @merchants_disabled.each do |merchant| %>
      <section id='merchant-<%= merchant.id %>'>
        <h3><%= link_to merchant.name, admin_merchant_path(merchant) %></h3>
        <ul>
          <li>City: <%= merchant.city%></li>
          <li>Merchant: <%= merchant.state%></li>
          <li>Enrolled since: <%= merchant.created_at%></li>
          <li><%= link_to 'Enable', admin_merchant_path(merchant, enable: true), method: :patch %></li>
        </ul>
      </section>
    <% end %>
  <% end %>
</section>

app/views/merchants/show.html.erb
<%= render partial: 'users/show' %>

<%= link_to "View my Items", dashboard_items_path %>

<section id="top-5-items-sold">
  <h1>Top 5 Items Sold</h1>
<ul>
  <% @top_five_items_sold.each do |item|  %>
  <li><%= item.name %> - <%= item.quantity_sold %></li>
  <% end %>
</ul>
</section>

<section id="percent-inventory-sold">
  <h1>Inventory Stats</h1>
  <p>Sold <%= @user.items_sold %> items, which is <%= @user.percent_inventory_sold %>% of your total inventory.</p>
</section>

<section id="top-3-states">
  <h1>Top Three States</h1>
  <p>
    <% @user.top_three_states_with_quantity_sold.each do |relation| %>
    <%= relation.state %> - <%= relation.quantity_sold %> items
    <% end %>
  </p>
</section>

<% if @best_customer_by_orders %>
<section id="best-customers">
  <p>Best customer by orders: <%= @best_customer_by_orders.name %> - <%= @best_customer_by_orders.order_count %> orders</p>
  <p>Best customer by items: <%= @best_customer_by_items.name %> - <%= @best_customer_by_items.items_ordered %> items</p>
  <p>Best customers by revenue:
    <% @best_customers_by_revenue.each do |customer| %>
    <%= customer.name %> - $<%= customer.revenue %>
    <% end %>
  </p>
</section>
<% end %>

<section id='pending-orders'>
  <% @pending_orders.each do |order| %>
  <section id="pending-order-card-<%= order.id %>">
    <p><%= link_to order.id, dashboard_order_path(order) %>,
    <%= order.created_at %>, Quantity: <%= order.total_quantity %>,
    Total Value: $<%= order.grand_total %>
    </p>
  </section>
  <% end %>
</section>