config/routes.rb
Rails.application.routes.draw do
  #general routes
  root to: "welcome#index"
  resources :items, only: [:index, :show, :destroy]
  resources :orders, only: [:show, :update]

  #merchant routes
  resources :items, only: [:new, :create, :index, :show, :destroy]

  resources :merchants, only: [:index, :show] do
    resources :items, only: [:show]
  end

  get '/dashboard', to: 'merchants#show', as: :dashboard
  get '/dashboard/orders/:id', to: 'merchants/orders#show', as: :dashboard_order
  get '/dashboard/items', to: 'merchants/items#index', as: :dashboard_items
  get '/dashboard/items/new', to: 'merchants/items#new', as: :new_merchant_item
  get '/dashboard/items/:id/edit', to: 'merchants/items#edit', as: :edit_item
  patch '/dashboard/items/:id/edit', to: 'merchants/items#update'
  get '/enable_item/:id', to: 'merchants/items#enable_item', as: :enable_item
  get '/fulfill_item/:id', to: 'merchants/items#fulfill_item', as: :fulfill_item
  get '/delete_item/:id', to: 'merchants/items#delete_item', as: :delete_item
  get '/disable_item/:id', to: 'merchants/items#disable_item', as: :disable_item

  #admin routes
  namespace :admin do
    get '/dashboard', to: 'users#dashboard', as: :dashboard
    resources :merchants, only: [:show, :update]
    resources :users, only: [:show, :index, :update]
  end

  #cart routes
  get '/cart', to: "cart#index", as: :cart
  get '/emptycart', to: "cart#destroy", as: :empty_cart
  get '/remove_item/:id', to: "cart#remove_item", as: :remove_item
  get '/increment_item/:id', to: "cart#increment_item", as: :increment_item
  get '/decrement_item/:id', to: "cart#decrement_item", as: :decrement_item
  get '/checkout', to: "cart#checkout", as: :checkout

  #user routes
  get '/profile', to: "users#show", as: :profile
  get '/profile/edit', to: "users#edit", as: :edit_profile
  get '/profile/orders', to: "orders#index", as: :profile_orders
  get '/profile/orders/:id', to: "orders#show", as: :profile_order
  resources :cart, only: [:create]

  #all users routes
  get '/login', to: "sessions#new", as: :login
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: :logout
  get '/register', to: "users#new", as: :registration
  resources :users, only: [:new, :create, :edit, :update] do
    resources :items, only: [:create]
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LittleCoffeeShop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Little Coffee Shop</a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item nav-link"><%= link_to "Home", root_path %></li>
          <li class="nav-item nav-link"><%= link_to "Items", items_path %></li>
          <li class="nav-item nav-link"><%= link_to "Merchants", merchants_path %></li>

          <% unless current_user %>
            <li class="nav-item nav-link"><%= link_to "Login", login_path %></li>
            <li class="nav-item nav-link"><%= link_to "Register", registration_path %></li>
          <% end %>

          <% if current_reguser? %>
            <li class="nav-item nav-link"><%= link_to "Profile", profile_path %></li>
          <% elsif merchant_user? %>
            <li class="nav-item nav-link"><%= link_to "Dashboard", dashboard_path %></li>
          <% elsif admin_user? %>
            <li class="nav-item nav-link"><%= link_to "Dashboard", admin_dashboard_path(current_user) %></li>
            <li class="nav-item nav-link"><%= link_to 'Users', admin_users_path %></li>
          <% end %>

          <% if current_user %>
            <li class="nav-item nav-link"><%= link_to "Logout", logout_path %></li>
          <% end %>

          <% unless merchant_user? || admin_user? %>
            <li class="nav-item nav-link"><%= link_to "Cart", cart_path %>: <%= @cart.total_count %></li>
          <% end %>
        </ul>
          <span class="navbar-text">
            <% if current_user %>
              Logged in as <%= current_user.name %>
            <% end %>
          </span>
      </div>

    </nav>

    <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: type %>
    <% end %>
    <div class="container-fluid yield">
       <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>